---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    component: secrets
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "n8n" # <------ Change Me!
  # Basic auth credentials
  N8N_BASIC_AUTH_PASSWORD: "n8n" # <------ Change Me!
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "n8n" # <------ Change Me!
  N8N_SECURE_COOKIE: "false"
